#!/bin/bash
# Loop through all directories in the base directory
for dir in "deploy"/*/; do
    # Check if the 'key' file exists in the current directory
    if [ -f "${dir}key" ]; then
        echo "Deleting file: ${dir}key"
        rm "${dir}key"  # Delete the 'key' file
    else
        echo "No 'key' file found in: $dir"
    fi
done

./delete_all_workflows
git add . && git commit -m "Deployment attempt on $(date '+%Y-%m-%d %H:%M:%S')" && git push origin 241209
./watch_current_workflow

