#!/bin/bash

while true; do
  # Get the latest workflow run ID
  latest_run_id=$(gh run list --json databaseId -q '.[0].databaseId')

  # Check if a workflow run was found
  if [ -z "$latest_run_id" ]; then
    echo "No workflow runs found in this repository."
    exit 0
  fi

  gh run watch "$latest_run_id"
  sleep 1
done