#!/bin/bash

check_info_yml() {
    local DIR_PATH="$1"
    if [ ! -f "$DIR_PATH/info.yml" ]; then
        echo "Error: info.yml not found in directory '$DIR_PATH'"
        exit 1
    fi
}

handle_key_zip() {
    local DIR_PATH="$1"
    if [ ! -f "$DIR_PATH/key.zip" ]; then
        echo "Error: key.zip not found in directory '$DIR_PATH'"
        exit 1
    fi
    echo "Unzipping key.zip in $DIR_PATH"
    unzip -o -P "241120" "$DIR_PATH/key.zip" -d "$DIR_PATH"
    
    if [ ! -f "$DIR_PATH/key" ]; then
        echo "Error: SSH key file 'key' not found in directory '$DIR_PATH' after unzipping"
        exit 1
    fi
    chmod 600 "$DIR_PATH/key"
}

read_yaml_values() {
    local DIR_PATH="$1"
    HOSTNAME=$(yq '.general.hostname' "$DIR_PATH/info.yml")
    USER=$(yq '.general.user' "$DIR_PATH/info.yml")
    SERVER_IP=$(yq '.general.server_ip' "$DIR_PATH/info.yml")
    PORT=$(yq '.general.port' "$DIR_PATH/info.yml")

    BINARY_PATH=$(yq '.paths.binary_path' "$DIR_PATH/info.yml")
    CONFIG_PATH=$(yq '.paths.config_path' "$DIR_PATH/info.yml")
    DEST_PATH=$(yq '.paths.dest_path' "$DIR_PATH/info.yml")
}

create_remote_directory() {
    local DIR_PATH="$1"
    echo "Connecting to $HOSTNAME at $SERVER_IP:$PORT as $USER"
    ssh -o StrictHostKeyChecking=no -i "$DIR_PATH/key" -p "$PORT" "$USER@$SERVER_IP" bash -c "'
        if [ -e \"$DEST_PATH\" ]; then
            if [ -d \"$DEST_PATH\" ]; then
                echo \"Directory already exists.\"
            else
                echo \"A file with the same name exists. Aborting.\"
                exit 1
            fi
        else
            mkdir -p \"$DEST_PATH\"
            echo \"Directory created.\"
        fi
        '"
    
    # Clean up the key file
    rm "$DIR_PATH/key"
    echo "Removed key file for security"
}

# Main script
if [ ! -d "deploy" ]; then
    echo "Error: Directory 'deploy' not found"
    exit 1
fi

for dir in deploy/*/; do
    DIR_PATH=$(realpath "$dir")
    echo "- $DIR_PATH"
    
    check_info_yml "$DIR_PATH"
    handle_key_zip "$DIR_PATH"
    read_yaml_values "$DIR_PATH"
    create_remote_directory "$DIR_PATH"
done

exit 0