#!/bin/bash
# Read values from the YAML file
HOSTNAME=$(yq '.general.hostname' info.yml)
USER=$(yq '.general.user' info.yml)
SERVER_IP=$(yq '.general.server_ip' info.yml)
PORT=$(yq '.general.port' info.yml)

# Read paths
BINARY_PATH=$(yq '.paths.binary_path' info.yml)
CONFIG_PATH=$(yq '.paths.config_path' info.yml)
DEST_PATH=$(yq '.paths.dest_path' info.yml)

# Example usage of the variables
echo "Connecting to $HOSTNAME at $SERVER_IP:$PORT as $USER"
echo "Binary path: $BINARY_PATH"
echo "Config path: $CONFIG_PATH"
echo "Destination path: $DEST_PATH"

# Use SFTP to transfer files
(cd && sftp -o StrictHostKeyChecking=no -i "key" -P "$PORT" "$USER@$SERVER_IP" <<EOF
put "$BINARY_PATH" "$DEST_PATH/virtual_meter_server"
put -r "$CONFIG_PATH" "$DEST_PATH/$CONFIG_PATH"  # Upload the config directory recursively
EOF)


rm "key"


