#!/bin/bash
for dir in deploy/*/; do
    # Read values from the YAML file
    HOSTNAME=$(yq '.general.hostname' $dir/info.yml)
    USER=$(yq '.general.user' $dir/info.yml)
    SERVER_IP=$(yq '.general.server_ip' $dir/info.yml)
    PORT=$(yq '.general.port' $dir/info.yml)

    # Read paths
    BINARY_PATH=$(yq '.paths.binary_path' $dir/info.yml)
    CONFIG_PATH=$(yq '.paths.config_path' $dir/info.yml)
    DEST_PATH=$(yq '.paths.dest_path' $dir/info.yml)

    # Example usage of the variables
    echo "Connecting to $HOSTNAME at $SERVER_IP:$PORT as $USER"
    echo "Binary path: $BINARY_PATH"
    echo "Config path: $CONFIG_PATH"
    echo "Destination path: $DEST_PATH"

    # Use SFTP to transfer files
    sftp -o StrictHostKeyChecking=no -i "$dir/key" -P "$PORT" "$USER@$SERVER_IP" <<EOF
put "$BINARY_PATH" "$DEST_PATH/virtual_meter_server"
put -r "$CONFIG_PATH" "$DEST_PATH/$CONFIG_PATH"  # Upload the config directory recursively
EOF
    rm "$dir/key"


done
