meter_data:
  ip: "127.0.0.1"
  port: 5020
  meter_type: "Phoenix Generic"

auth:
  name: "admin"
  register: 16403
  pin: 100

write_registers:
  - name: power_factor_L1
    address: 32816
    value: 10
  - name: power_factor_L2
    address: 32818
    value: 20
  - name: power_factor_L3
    address: 32820
    value: 30

read_registers:
  - name: voltage_L1_N
    address: 32774
    value: 230
  - name: voltage_L2_N
    address: 32776
    value: 231
  - name: voltage_L3_N
    address: 32778
    value: 229
  - name: current_L1_N
    address: 32782
    value: 15
  - name: current_L2_N
    address: 32784
    value: 14
  - name: current_L3_N
    address: 32786
    value: 16
  - name: active_power_L1_N
    address: 32798
    value: 3450
  - name: active_power_L2_N
    address: 32800
    value: 3400
  - name: active_power_L3_N
    address: 32802
    value: 3500
  - name: reactive_power_L1_N
    address: 32804
    value: 1200
  - name: reactive_power_L2_N
    address: 32806
    value: 1150
  - name: reactive_power_L3_N
    address: 32808
    value: 1180
  - name: power_factor_L1
    address: 32816
    value: 10
  - name: power_factor_L2
    address: 32818
    value: 20
  - name: power_factor_L3
    address: 32820
    value: 30
  - name: grid_frequency
    address: 32780
    value: 50
  - name: total_current
    address: 32825
    value: 45
  - name: total_active_power
    address: 32790
    value: 10350
  - name: total_apparent_power
    address: 32794
    value: 12500
  - name: total_reactive_power
    address: 32792
    value: 3530

debug:
  mgw_generic: "info"
  statemachine_modbus: "info"
  statemachine_read: "info"
