name: Rust CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PK_BACHELOR_DEPLOY }}
      run: |
        echo "The secret value is: $SSH_PRIVATE_KEY"
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa

    - name: Create remote directory
      run: |
        USER="deploy"
        SERVER_IP="217.160.9.123"
        PORT="47122"
        DIR_PATH="/home/deploy/virtual_meter_server"
        
    
        ssh -o StrictHostKeyChecking=no -i "id_rsa" -p "$PORT" "$USER@$SERVER_IP" bash -c "'
        if [ -e \"$DIR_PATH\" ]; then
            if [ -d \"$DIR_PATH\" ]; then
                echo \"Directory already exists.\"
            else
                echo \"A file with the same name exists. Aborting.\"
                exit 1
            fi
        else
            mkdir -p \"$DIR_PATH\"
            echo \"Directory created.\"
        fi
        '"

    - name: Upload deploy directory
      uses: actions/upload-artifact@v3
      with:
        name: deploy
        path: |
          deploy/**  # Include all files in the deploy directory

    - name: Install yq yaml bash processor
      run: |
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod a+x /usr/local/bin/yq

    # Leaves the decrypted key in the deploy/*/ directory
    - name: Loop through deploy directory check every target directory
      run: |
        for dir in deploy/*/; do
          (cd $dir && chmod +x check_target_dir && ./check_target_dir)
        done

    - name: Exit workflow
      run: |
        pwd
        exit 1

    - name: Create artifact (Set up Rust)
      uses: actions-rs/toolchain@v1.0.0
      with:
        toolchain: stable
        override: true

    - name: Create artifact (Build)
      run: cargo build --release --verbose

    # - name: Run tests
    #   run: cargo test --verbose

    # - name: List target directory
    #   run: ls -R target/

    - name: Upload binary and config directory
      uses: actions/upload-artifact@v3
      with:
        name: virtual_meter_server
        path: |
          target/release/virtual_meter_server
          config/**  # Include all files in the config directory

    - name: Debug Artifact location
      run: |
        stat target/release/virtual_meter_server
        pwd






    - name: Transfer binary and config via SFTP
      run: |
        for dir in deploy/*/; do
          (cd $dir && chmod +x transfer_artifact && ./transfer_artifact)
        done
       
